Repository ucsb-cs156-f23/proj-courses-f23-7pm-2, pull requests merged in 2023-11, with the labels that each got.

#16 Added course status to sections table
  frontend/src/fixtures/sectionFixtures.js
  frontend/src/fixtures/sectionOverTimeFixtures.js
  frontend/src/main/components/Sections/SectionsOverTimeTable.js
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/main/utils/sectionUtils.js
  frontend/src/tests/components/Sections/SectionsOverTimeTable.test.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
Labels: FIXME-Peer CR

#20 Implemented Feature: Devs can see github branch info
  frontend/src/App.js
  frontend/src/main/pages/DeveloperPage.js
  frontend/src/stories/pages/DeveloperPage.stories.js
  frontend/src/tests/pages/DeveloperPage.test.js
  pom.xml
  src/main/java/edu/ucsb/cs156/courses/CoursesApplication.java
  src/main/java/edu/ucsb/cs156/courses/models/SystemInfo.java
  src/main/java/edu/ucsb/cs156/courses/services/SystemInfoServiceImpl.java
Labels: 10, merge candidate

#33 Reformatted the personal schedules details page test to use fixtures instead of being hardcoded
  frontend/src/fixtures/personalScheduleFixtures.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesDetailsPage.test.js
Labels: 5, merge candidate

#17 Ray - Fix Bug: Creating personal schedule fails first try until quarter field changed
  frontend/src/main/components/Quarters/SingleQuarterDropdown.js
  frontend/src/tests/components/Quarters/SingleQuarterDropdown.test.js
Labels: 10, merge candidate

#19 Course Details Page
  frontend/src/App.js
  frontend/src/fixtures/personalSectionsFixtures.js
  frontend/src/main/components/CourseDetails/CourseDetailsTable.js
  frontend/src/main/pages/CourseDetails/CourseDetailsIndexPage.js
  frontend/src/stories/components/CourseDetails/CourseDetailsTable.stories.js
  frontend/src/stories/pages/CourseDetailsIndexPage.stories.js
  frontend/src/tests/components/CourseDetails/CourseDetailsTable.test.js
  frontend/src/tests/pages/CourseDetails/CourseDetailsIndexPage.test.js
Labels: 10, merge candidate

#31 Changed Stryker Enable to Restore
  frontend/src/main/components/Courses/CourseForm.js
  frontend/src/main/components/Courses/CourseTable.js
  frontend/src/main/components/Jobs/TestJobForm.js
  frontend/src/main/components/Jobs/UpdateCoursesByQuarterJobForm.js
  frontend/src/main/components/PersonalSchedules/PersonalScheduleForm.js
  frontend/src/main/components/PersonalSchedules/PersonalSchedulesTable.js
  frontend/src/main/components/Sections/SectionsOverTimeTable.js
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/main/components/UCSBSubjects/UCSBSubjectsTable.js
  frontend/src/main/components/Utils/Plaintext.js
  frontend/src/main/pages/AdminJobsPage.js
  frontend/src/main/utils/useBackend.js
  frontend/src/tests/components/Jobs/TestJobsForm.test.js
  frontend/src/tests/components/PersonalSchedules/PersonalScheduleForm.test.js
  frontend/src/tests/components/PersonalSchedules/PersonalSchedulesTable.test.js
  frontend/src/tests/components/UCSBSubjects/UCSBSubjectsTable.test.js
Labels: 10, merge candidate

#29 Tiger - FEATURE: MVP (placeholder) for Course Details page - F2: Button to route to placeholder page
  frontend/public/index.html
  frontend/src/main/components/Sections/SectionsOverTimeTable.js
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/main/utils/sectionUtils.js
  frontend/src/tests/components/Sections/SectionsOverTimeTable.test.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
  frontend/src/tests/utils/sectionUtils.test.js
Labels: 10, merge candidate
